-- 1-A

SHOW DATABASES;
SHOW SCHEMAS;

-- 2-A
CREATE DATABASE BANCOSPJ;
USE BANCOSPJ;

-- 2-B
CREATE SCHEMA BANCOSPJ;
USE BANCOSPJ;

-- 3-A
CREATE TABLE FORNECEDORES (
	CODS INT,
    SNAME CHAR(10) NOT NULL,
    STATUS INT,
    PRIMARY KEY (CODS)
);

-- 3-B
CREATE TABLE FORNECEDORES (
	CODS INT PRIMARY KEY,
    SNAME CHAR(10) NOT NULL,
    STATUS INT
);

 -- 7-B
 ALTER TABLE FORNECEDORES
	RENAME TO S;
    
 -- 8
UPDATE S SET CITY="BRASILIA"
	WHERE CODS=5;
    
 -- 9
DELETE FROM S
	WHERE CODS=4;
    
DELETE FROM S
	WHERE SNAME="CLARK" AND CITY="LONDON";
    
 -- 10-A
CREATE DATABASE TEMP;
 
  -- 11
insert into s values (5,"JOE", 50, "GOIANIA");
 
 -- 12
CREATE TABLE P (
	CODP INT,
    PNAME CHAR(6) NOT NULL,
    CORES CHAR(6),
    PRIMARY KEY(CODP)
);

-- 13
INSERT INTO P VALUES
(1, "NUT", "RED"), (2, "BOLT", "GRENN"),
(3, "SCREW", "BLUE"), (4, "SCREW", "RED"),
(5, "CAM", "BLUE"), (6, "COG", "RED");

-- 14-A
CREATE TABLE J (
	CODJ INT PRIMARY KEY,
    JNAME CHAR(10) NOT NULL,
    CITY CHAR(10)
);

-- 15
INSERT INTO J VALUES
	(1, "SORTER", "PARIS"), (2, "PUNCH", "ROME"),
    (3, "READER", "ATHENS"), (4, "CONSOLE", "ATHENS");
    
-- 16
CREATE TABLE SPJ(
	CODS INT,	
    CODP INT,	
    CODJ INT,
    QTY  INT NOT NULL,
    PRIMARY KEY (CODS, CODP, CODJ),
    FOREIGN KEY (CODS) REFERENCES S(CODS),
    FOREIGN KEY (CODP) REFERENCES S(CODP),
    FOREIGN KEY (CODJ) REFERENCES S(CODJ)
);

DROP TABLE SPJ;


